version: "3"
services:
  postgis:
    image: geographica/postgis:tasty_termite
    ports:
      - "5433:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres
volumes:
  db-data:

